# Generated by Django 4.2.11 on 2024-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_developer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.CharField(default='18-06-2024 07:01', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='position',
            field=models.CharField(choices=[('frontend', 'FrontEnd'), ('backend', 'BackEnd'), ('designer', 'Designer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='updated_at',
            field=models.CharField(default='18-06-2024 07:01', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='created_at',
            field=models.CharField(default='18-06-2024 07:01', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='updated_at',
            field=models.CharField(default='18-06-2024 07:01', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.CharField(default='18-06-2024 07:01', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.CharField(default='18-06-2024 07:01', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='18-06-2024 07:01', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='18-06-2024 07:01', max_length=20),
        ),
    ]
