# Generated by Django 4.2.11 on 2024-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_team_options_alter_developer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.CharField(default='21-06-2024 12:06', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='updated_at',
            field=models.CharField(default='21-06-2024 12:06', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='created_at',
            field=models.CharField(default='21-06-2024 12:06', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='updated_at',
            field=models.CharField(default='21-06-2024 12:06', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.CharField(default='21-06-2024 12:06', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.CharField(default='21-06-2024 12:06', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='21-06-2024 12:06', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='21-06-2024 12:06', max_length=20),
        ),
    ]
