# Generated by Django 4.2.11 on 2024-06-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_developer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subteam',
            name='status',
            field=models.CharField(choices=[('refused', 'Rad Etilgan'), ('pending', 'Kutilyapti'), ('accepted', 'Qabul qilingan')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.CharField(default='24-06-2024 06:23', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='updated_at',
            field=models.CharField(default='24-06-2024 06:23', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='created_at',
            field=models.CharField(default='24-06-2024 06:23', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='updated_at',
            field=models.CharField(default='24-06-2024 06:23', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.CharField(default='24-06-2024 06:23', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.CharField(default='24-06-2024 06:23', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='24-06-2024 06:23', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='24-06-2024 06:23', max_length=20),
        ),
    ]
