# Generated by Django 4.2.11 on 2024-06-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subteam_status_alter_developer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.CharField(default='28-06-2024 07:55', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='updated_at',
            field=models.CharField(default='28-06-2024 07:55', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='created_at',
            field=models.CharField(default='28-06-2024 07:55', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='status',
            field=models.CharField(choices=[('refused', 'Rad Etilgan'), ('pending', 'Jarayonda'), ('accepted', 'Qabul qilingan')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='updated_at',
            field=models.CharField(default='28-06-2024 07:55', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.CharField(default='28-06-2024 07:55', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.CharField(default='28-06-2024 07:55', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='28-06-2024 07:55', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='28-06-2024 07:55', max_length=20),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('busy', 'Band'), ('free', 'Bosh')], default='free', max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
        ),
    ]
