# Generated by Django 4.2.11 on 2024-07-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_address_alter_announcement_person_and_more'),
        ('users', '0009_alter_developer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subteam',
            name='request',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='announcements.workrequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.CharField(default='08-07-2024 08:04', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='updated_at',
            field=models.CharField(default='08-07-2024 08:04', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='created_at',
            field=models.CharField(default='08-07-2024 08:04', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='updated_at',
            field=models.CharField(default='08-07-2024 08:04', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.CharField(default='08-07-2024 08:04', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.CharField(default='08-07-2024 08:04', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='08-07-2024 08:04', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='08-07-2024 08:04', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='created_at',
            field=models.CharField(default='08-07-2024 08:04', max_length=20),
        ),
    ]
