# Generated by Django 5.0.6 on 2024-10-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subteam_request_alter_developer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subteam',
            name='request',
        ),
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.CharField(default='08-10-2024 16:15', max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='updated_at',
            field=models.CharField(default='08-10-2024 16:15', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='created_at',
            field=models.CharField(default='08-10-2024 16:15', max_length=20),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='updated_at',
            field=models.CharField(default='08-10-2024 16:15', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.CharField(default='08-10-2024 16:15', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.CharField(default='08-10-2024 16:15', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default='08-10-2024 16:15', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.CharField(default='08-10-2024 16:15', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='created_at',
            field=models.CharField(default='08-10-2024 16:15', max_length=20),
        ),
    ]
