version: '3.13'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/projectmanager
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: NAME
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD

volumes:
  postgres_data: