# Generated by Django 5.0.6 on 2024-07-04 12:28

import announcements.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('jismoniy', 'Jismoniy shaxs'), ('yuiridik', 'Yuridik shaxs')], max_length=50, null=True)),
                ('project_name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('cost', models.IntegerField()),
                ('tashkilot_nomi', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=700)),
                ('phone', models.CharField(help_text='+998 bilan kiriting!!!', max_length=15)),
                ('name_of_employer', models.CharField(max_length=30)),
                ('file1', models.FileField(null=True, storage=announcements.storages.CustomFileSystemStorage(), upload_to='documents')),
                ('file2', models.FileField(null=True, storage=announcements.storages.CustomFileSystemStorage(), upload_to='documents')),
                ('file3', models.FileField(null=True, storage=announcements.storages.CustomFileSystemStorage(), upload_to='documents')),
                ('remove_file1', models.BooleanField(default=False)),
                ('remove_file2', models.BooleanField(default=False)),
                ('remove_file3', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('refused', 'Rad Etilgan'), ('pending', 'Kutilyapti'), ('accepted', 'Qabul qilingan')], default='pending', max_length=50)),
                ('deadline', models.DateField()),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
