# Generated by Django 5.0.6 on 2024-07-04 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted_at': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='announcement',
            field=models.ForeignKey(limit_choices_to={'assigned_to': None, 'deleted_at': None}, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
