# Generated by Django 4.2.11 on 2024-06-05 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted_at': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='document',
            field=models.OneToOneField(limit_choices_to={'deleted_at': None}, on_delete=django.db.models.deletion.PROTECT, to='announcements.document'),
        ),
        migrations.AlterUniqueTogether(
            name='workrequest',
            unique_together={('announcement', 'requester')},
        ),
    ]
