# Generated by Django 5.0.6 on 2024-07-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='address',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='person',
        ),
    ]
