# Generated by Django 4.2.11 on 2024-06-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workrequest',
            unique_together=set(),
        ),
    ]
