# Generated by Django 5.0.6 on 2024-10-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_remove_announcement_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workrequest',
            options={'ordering': ['-id']},
        ),
    ]
