# Generated by Django 4.2.11 on 2024-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_workrequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='person',
            field=models.CharField(choices=[('jismoniy', 'Jismoniy shaxs'), ('yuiridik', 'Yuridik shaxs')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default='documents/dashboard.css', upload_to='documents'),
            preserve_default=False,
        ),
    ]
