# Generated by Django 5.0.6 on 2024-10-08 16:15

import announcements.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_address_alter_announcement_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='document',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='workrequest',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='address',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='person',
        ),
        migrations.AddField(
            model_name='announcement',
            name='file1',
            field=models.FileField(null=True, storage=announcements.storages.CustomFileSystemStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='file2',
            field=models.FileField(null=True, storage=announcements.storages.CustomFileSystemStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='file3',
            field=models.FileField(null=True, storage=announcements.storages.CustomFileSystemStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='remove_file1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='remove_file2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='remove_file3',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
